
server:
  port: 8081
temp:
  picture:
    tinypng:
      apikey: JKwWUnDJK2TsriXiBXzoKzziSnKHk3lh
      enable: false
jwt:
  secret: 123456
root:
  password: 123456
  avatar: https://gss0.bdstatic.com/94o3dSag_xI4khGkpoWK1HF6hhy/baike/w%3D268%3Bg%3D0/sign=27ac483e40a7d933bfa8e3759570b62e/5882b2b7d0a20cf419b28cf574094b36acaf99fd.jpg
  username: admin

spring:
  profiles:
    active: windows
  servlet:
    multipart:
      max-file-size: 1000MB
      file-size-threshold: 1
  http:
    encoding:
      force-response: true
      force-request: true
      charset: utf-8
      force: true


